language: scala
dist: xenial
os:
  - linux
env:
  global:
    - TRAVIS_NODE_VERSION="8"

script:
  - git checkout .
  - git clean -df
  - sbt cachedCiTest

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  - rm -rf ./.git
  - rm -rf ./project/target #clean doesn't clean meta-build

cache:
  yarn: true
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - ./